name: AmazingTitles
api-version: 1.13
version: 6.1-STABLE
main: org.korastudios.amazingtitles.code.internal.Booter
author: Kora Studios LLC
softdepend:
  - CMI
commands:
  amazingtitles:
    permission: "amazingtitles.command"
    aliases:
      - at
